config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :votes
  resources :posts
  resources :subjects
  resources :users

  # get '/users/'
  # get '/comments/new' => 'post#new'

  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create'

  delete '/subjects/:id/unfollow', to: 'subjects#unfollow', as: 'unfollow_subject'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :votes, as: :votable

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  has_many :comments
  has_many :votes, as: :votable

  validates :title, presence: true
  validates :content, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :posts
  has_many :comments, through: :posts
  has_many :user_subjects
  has_many :users, through: :user_subjects

  # validates :title, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :votes
  has_many :user_subjects
  has_many :subjects, through: :user_subjects
  has_many :comments, through: :posts

  validates :username, uniqueness: true
  # validates :password, presence: true
  validates :name, presence: true



  def count_post
     if !self.posts.empty?
        "You’ve submitted #{self.posts.count} post(s)."
     else
        "You don’t have any posts"
     end
   end

   def count_comments
     if !self.comments.empty?
      "You’ve submitted #{self.comments.count} comments."
    else
      "You don’t have any comments."
   end
  end

  def count_subjects
   if !self.subjects.empty?
     "You’re following #{self.subjects.count} subject(s)."
   else
     "You’re not following any subjects."
   end
  end
end

app/models/user_subject.rb
class UserSubject < ApplicationRecord
  belongs_to :user
  belongs_to :subject
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

def like
  
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController

  # def index
  #
  # end
  #
  # def show
  #
  # end
  #
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user


  def current_user
    @user ||= User.find_by(id: session[:user_id]) 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :delete]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.create(comment_params)

    redirect_to comment_path(@comment)
  end

  def edit

  end

  def update

    redirect_to comment_path(@comment)
  end

  def delete
    @comment.delete
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :delete]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.valid?
      @post.save

      redirect_to post_path(@post)
    else

      render :new
    end
  end

  def edit

  end

  def update
    @comment = Comment.new(comment_params)
    @comment.post_id = @post.id
    @comment.user_id = current_user
    # TODO add actual user_id
    @comment.save
    @post.comments << @comment
    redirect_to post_path(@post)
  end

  def delete
    @post.delete
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    # byebug
    @user = User.find_by(username: params[:session][:username])

    if @user.nil?
      redirect_to new_user_path
    # session[:user] = par
    else
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    end
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :delete, :unfollow]

  def index
    @subjects = Subject.all
  end

  def show

  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.valid?
      @subject.save

      redirect_to subject_path(@subject)
    else

      render :new
    end

  end

  def edit
    puts "arb"
  end

  def update


    redirect_to subject_path(@subject)
  end

  def unfollow
    # binding.pry
    current_user.subjects.delete(@subject)
    redirect_to user_path(@user)
  end

  def delete
    @subject.delete
  end

  private

  def subject_params
    params.require(:subject).permit(:title)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user

  def index
    @users = User.all
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to user_path(@user)
    else
      render :new
    end

  end

  def edit

  end

  def update
    current_user.subjects << Subject.find(params[:subject_id])
    
    redirect_to user_path(@user)
  end

  def delete
    @user.delete
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :delete]

  def index
    @votes = Vote.all
  end

  def show
  end

  def new
    @vote = Vote.new
  end

  def create
    @vote = Vote.create(vote_params)

    redirect_to vote_path(@vote)
  end

  def edit

  end

  def update

    redirect_to vote_path(@vote)
  end

  def delete
    @vote.delete
  end

  private

  def vote_params
    params.require(:vote).permit(:rank)
  end

  def set_vote
    @vote = Vote.find(params[:id])
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/edit.html.erb
<h1>Edit Comment Form</h1>
<%= form_for(@comment) do |f| %>

  Content: <%= f.text_field :content %><br>

  <%= f.submit "Submit Updated Post" %><br>

  <% end %>

app/views/comments/index.html.erb
<h1>List of User Comments</h1>
<% @comments.each do |comment| %>
<%= link_to comment.content, comment_path(comment) %><br>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment Form</h1>
<%= form_for(@comment) do |f| %>

  Comment: <%= f.text_area :content %><br>

  <button class="ui button"><%= f.submit "Submit New Comment" %></button><br>

  <% end %>

app/views/comments/show.html.erb
<h1>show comments on post of subject</h1>

app/views/posts/edit.html.erb
<h1>Edit Post Form</h1>
<%= form_for(@post) do |f| %>

  Title: <%= f.text_field :title %><br>

  Content: <%= f.text_field :content %><br>

  <%= f.submit "Submit Updated Post" %><br>

  <% end %>

app/views/posts/index.html.erb
<h1>List of User Posts</h1>
<% @posts.each do |post| %>
<%= link_to post.title, post_path(post) %><br>
<% end %>

app/views/posts/new.html.erb
<h1>New Post Form</h1>
<%= form_for(@post) do |f| %>

  Title: <%= f.text_field :title %><br>

  Content: <%= f.text_field :content %><br>

  <%= f.submit "Submit New Post" %><br>

  <% end %>

app/views/posts/show.html.erb
<h3><%= @post.title %></h3>
<p><%= @post.content %></p>

<div><button class="ui button"><%= link_to "Home", user_url %></button></div>

<%= form_for @comment, url: post_path(@post), method: "patch" do |f| %>
  Add Comment: <%= f.text_area :content %>
  <%= f.submit %><br>
  <% end %>
<br>
<br>
<br>

 <% @post.comments.each do |comment| %>
   <li><%= comment.content %><li><br>
 <% end %>

app/views/subjects/edit.html.erb
# do not need right now

app/views/subjects/index.html.erb
<h1>Subjects</h1>
<% @subjects.each do |subject| %>
<li><%= link_to subject.title, subject_path(subject) %></li>
<% end %>

app/views/subjects/new.html.erb
<h1>Create New Topic</h1>

<%= form_for(@subject) do |f| %>

  Title: <%= f.text_field :title %><br>

  <%= f.submit "Submit New Topic" %><br>

  <% end %>

app/views/subjects/show.html.erb
<div><h2><%= @subject.title %></h2></div>

 <% if current_user.subjects.include?(@subject) %>
  <%= button_to("Unfollow", unfollow_subject_path, :method => :delete, params: {subject_id: @subject.id}) %>
<% else %>
  <%= button_to("Follow", user_path(current_user), :method => :patch, params: {subject_id: @subject.id}) %>
<% end %>


<div><button><%= link_to "Home", user_url %></button></div>
<div><button><%= link_to "Create New Post", new_post_path %></button></div>
<% @subject.posts.each do |post| %>
  <%= link_to post.title, post %></br>



<% end %>

app/views/users/edit.html.erb
<h1>Edit User Form</h1>
<%= form_for(@user) do |f| %>

  <%= f.label :name  %>
  <%= f.text_field :name %><br>

  <%= f.label :username %>
  <%= f.text_field :username %><br>

  <%= f.label :password %>
  <%= f.text_field :password %><br>

  <%= f.submit "Update Account" %><br>

  <% end  %>

app/views/users/index.html.erb
<h1 class="ui center aligned icon header", align="center" >
  <i class="circular users icon"></i>
  Welcome to Netpost
</h1>

  <div align="center"><button class="ui button"><%= link_to "Login",  new_session_path %></button></div>
  <div align="center"><button class="ui button"><%= link_to "Create Account",  new_user_path %></button></div>

app/views/users/new.html.erb
<h1 class="ui center aligned icon header">
  <i class="circular users icon"></i>
  New User Form
</h1>

<%= form_for(@user) do |f| %>

  <div align="center"><%= f.label :name  %></div>
  <div align="center"><%= f.text_field :name %><br></div>

  <div align="center"><%= f.label :username %></div>
  <div align="center"><%= f.text_field :username %><br></div>

  <div align="center"><%= f.label :password %></div>
  <div align="center"><%= f.text_field :password %><br></div>

  <div align="center"><%= f.submit "Create Account" %><br></div>

  <% end  %>

app/views/users/show.html.erb
<div class="item">
  <div class="content">
    <div class="ui sub header">
      <div align="center"><h1><%= current_user.username if current_user %></h1></div>
    </div>
  </div>
</div>

<h2>Subjects</h2></br>


<div class="ui list">

<% if !current_user.subjects.empty? %>
  <% current_user.subjects.each do |subject| %>
  <div class="item">
  <h3><%= link_to subject.title, subject %></h3></br>
  </div>
  <% end %>
  <%= current_user.count_subjects %>
<% else %>
  <%= link_to 'All Subjects', subjects_path %>
<% end%><br><br>

<button class="ui button"><%= link_to 'Create Topic', new_subject_path %></button>
<button class="ui button"><%= link_to 'All Subjects', subjects_path %></button>

<h2>Posts</h2></br>
<% if !current_user.posts.empty? %>
  <% current_user.posts.each do |post| %>
  <div class="item">
    <h3><%= link_to post.title, post %></h3
       <%= current_user.count_post %>
  </div>
  <% end %>
  <%= current_user.count_post%>
<% else %>
<%= current_user.count_post %>
<% end%>

<h2>Comments</h2></br>
<% if !current_user.comments.empty? %>
  <% current_user.comments.each do |comment| %>
  <div class="item">
    <h3><%= comment.content%></h3>
  </div>
  <% end %>
  <%= current_user.count_comments%>
<% else %>
<%= current_user.count_comments%>
<% end%>

</div>

<!--
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= current_user.name %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="current_users">Home</a></li>
        <li><a href="/subjects">Subjects</a></li>
        <li><a href="/post">Top</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group input-group">
          <input type="text" class="form-control" placeholder="Search Postal..">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphiconcurrent_user"></span> My Account</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container text-center">
  <div class="row">
    <div class="col-sm-3 well">
      <div class="well">
        <p><%= link_to "My Profile", current_user %></p>
        <img src="bird.jpg" class="img-circle" height="65" width="65" alt="Avatar">
      </div>
      <div class="well">
        <p><a href="#">Interests</a></p>
        <p>
        <% current_user.subjects.each do |subject| %>
          <span class="label label-default"><%= subject.title %></span>
          <span class="label label-primary"><%= subject.title %></span>
          <span class="label label-success"><%= subject.title %></span>
          <span class="label label-info"><%= subject.title %></span>
          <span class="label label-warning"><%= subject.title %></span>
          <span class="label label-danger"><%= subject.title %></span>
          <% end %>
        <%= link_to 'Create Topic', new_subject_path %>
        </p>
      </div>
      <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <p><strong>Ey!</strong></p>
        People are looking at your profile. Find out who.
      </div>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
    </div>
    <div class="col-sm-7">

      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
              <p contenteditable="true">Status: Feeling Blue</p>
              <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
              </button>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>John</p>
           <img src="bird.jpg" class="img-circle" height="55" width="55" alt="Avatar">
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Bo</p>
           <img src="bandmember.jpg" class="img-circle" height="55" width="55" alt="Avatar">
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Jane</p>
           <img src="bandmember.jpg" class="img-circle" height="55" width="55" alt="Avatar">
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Anja</p>
           <img src="bird.jpg" class="img-circle" height="55" width="55" alt="Avatar">
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-2 well">
      <div class="thumbnail">
        <p>Upcoming Events:</p>
        <img src="paris.jpg" alt="Paris" width="400" height="300">
        <p><strong>Paris</strong></p>
        <p>Fri. 27 November 2015</p>
        <button class="btn btn-primary">Info</button>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>

</body>
</html>
-->